/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rahul/projects/Nimrod/lib -o /home/rahul/musings/nimrod/gtk/nimcache/gtk_gtk2.o /home/rahul/musings/nimrod/gtk/nimcache/gtk_gtk2.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tbutton106649 tbutton106649;
typedef struct twidget106465 twidget106465;
typedef struct twindow106531 twindow106531;
typedef struct tvbox106843 tvbox106843;
typedef struct thbox106871 thbox106871;
typedef struct tbox106629 tbox106629;
typedef struct tcontainer106511 tcontainer106511;
typedef struct tobject106409 tobject106409;
typedef struct tbin106519 tbin106519;
typedef struct tgobject79248 tgobject79248;
typedef struct tgtypeinstance77360 tgtypeinstance77360;
typedef struct tgtypeclass77356 tgtypeclass77356;
typedef struct tstyle107133 tstyle107133;
typedef struct trequisition106463 trequisition106463;
typedef struct tallocation96330 tallocation96330;
typedef struct twindow96224 twindow96224;
typedef struct twindowgroup106537 twindowgroup106537;
typedef struct tscreen96302 tscreen96302;
typedef struct tglist77386 tglist77386;
typedef struct tcolor96218 tcolor96218;
typedef struct tfontdescription91249 tfontdescription91249;
typedef struct tgc96280 tgc96280;
typedef struct tcolormap96356 tcolormap96356;
typedef struct tfont96244 tfont96244;
typedef struct trcstyle107115 trcstyle107115;
typedef struct tgslist77382 tgslist77382;
typedef struct tvisual96350 tvisual96350;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_CDECL_PTR(tbutton106649*, TY115755) (NCSTRING label);
typedef N_CDECL_PTR(void, TY113076) (twidget106465* widget);
typedef N_CDECL_PTR(void, TY122835) (void);
typedef NCSTRING TY141512[256];
typedef N_CDECL_PTR(void, TY122827) (void* argc, void* argv);
typedef N_CDECL_PTR(twindow106531*, TY114325) (NI32 thetype);
typedef N_CDECL_PTR(tvbox106843*, TY117510) (int homogeneous, int spacing);
typedef N_CDECL_PTR(thbox106871*, TY117676) (int homogeneous, int spacing);
typedef N_CDECL_PTR(void, TY115519) (tbox106629* box, twidget106465* child, int expand, int fill, int padding);
typedef N_CDECL_PTR(void, TY113887) (tcontainer106511* container, int borderwidth);
typedef N_CDECL_PTR(void, TY113896) (tcontainer106511* container, twidget106465* widget);
typedef N_CDECL_PTR(void, tsignalfunc106425) (void* para1);
typedef N_CDECL_PTR(NI, TY137405) (tobject106409* anobject, NCSTRING name, tsignalfunc106425 fun, void* unknown1, void* funcdata, void* unknown2, NI unknown3, NI unknown4);
typedef N_CDECL_PTR(void, TY122824) (void);
struct tgtypeinstance77360 {
tgtypeclass77356* Gclass;
};
struct tgobject79248 {
tgtypeinstance77360 Gtypeinstance;
int Refcount;
void* Qdata;
};
struct tobject106409 {
  tgobject79248 Sup;
NI32 Flags;
};
struct trequisition106463 {
int Width;
int Height;
};
struct tallocation96330 {
int X;
int Y;
int Width;
int Height;
};
struct twidget106465 {
  tobject106409 Sup;
NI16 Privateflags;
NI8 State;
NI8 Savedstate;
NCSTRING Name;
tstyle107133* Style;
trequisition106463 Requisition;
tallocation96330 Allocation;
twindow96224* Window;
twidget106465* Parent;
};
struct tcontainer106511 {
  twidget106465 Sup;
twidget106465* Focuschild;
NI32 Containerflag0;
};
struct tbin106519 {
  tcontainer106511 Sup;
twidget106465* Child;
};
struct tbutton106649 {
  tbin106519 Sup;
twindow96224* Eventwindow;
NCSTRING Labeltext;
int Activatetimeout;
NI16 Buttonflag0;
};
struct twindow106531 {
  tbin106519 Sup;
NCSTRING Title;
NCSTRING Wmclassname;
NCSTRING Wmclassclass;
NCSTRING Wmrole;
twidget106465* Focuswidget;
twidget106465* Defaultwidget;
twindow106531* Transientparent;
void* Geometryinfo;
twindow96224* Frame;
twindowgroup106537* Group;
NI16 Configurerequestcount;
NI32 Windowflag0;
int Frameleft;
int Frametop;
int Frameright;
int Framebottom;
int Keyschangedhandler;
int Mnemonicmodifier;
tscreen96302* Screen;
};
struct tbox106629 {
  tcontainer106511 Sup;
tglist77386* Children;
NI16 Spacing;
NI16 Boxflag0;
};
struct tvbox106843 {
  tbox106629 Sup;
};
struct thbox106871 {
  tbox106629 Sup;
};
struct tgtypeclass77356 {
NI Gtype;
};
struct tcolor96218 {
NI32 Pixel;
NI16 Red;
NI16 Green;
NI16 Blue;
};
typedef tcolor96218 TY110274[5];
typedef tgc96280* TY110303[5];
typedef twindow96224* TY110329[5];
struct tstyle107133 {
  tgobject79248 Sup;
TY110274 Fg;
TY110274 Bg;
TY110274 Light;
TY110274 Dark;
TY110274 Mid;
TY110274 Text;
TY110274 Base;
TY110274 Textaa;
tcolor96218 Black;
tcolor96218 White;
tfontdescription91249* Fontdesc;
int Xthickness;
int Ythickness;
TY110303 Fggc;
TY110303 Bggc;
TY110303 Lightgc;
TY110303 Darkgc;
TY110303 Midgc;
TY110303 Textgc;
TY110303 Basegc;
TY110303 Textaagc;
tgc96280* Blackgc;
tgc96280* Whitegc;
TY110329 Bgpixmap;
int Attachcount;
int Depth;
tcolormap96356* Colormap;
tfont96244* Privatefont;
tfontdescription91249* Privatefontdesc;
trcstyle107115* Rcstyle;
tgslist77382* Styles;
void* Propertycache;
tgslist77382* Iconfactories;
};
struct twindow96224 {
  tgobject79248 Sup;
};
struct twindowgroup106537 {
  tgobject79248 Sup;
tgslist77382* Grabs;
};
struct tscreen96302 {
  tgobject79248 Sup;
};
struct tglist77386 {
void* Data;
tglist77386* Next;
tglist77386* Prev;
};
struct tfontdescription91249 {
char dummy;
};
struct tgc96280 {
  tgobject79248 Sup;
int Clipxorigin;
int Clipyorigin;
int Tsxorigin;
int Tsyorigin;
tcolormap96356* Colormap;
};
struct tcolormap96356 {
  tgobject79248 Sup;
int Size;
tcolor96218* Colors;
tvisual96350* Visual;
void* Windowingdata;
tscreen96302* Screen;
};
struct tfont96244 {
NU8 Type;
int Ascent;
int Descent;
};
typedef NCSTRING TY110172[5];
typedef NI32 TY110176[5];
struct trcstyle107115 {
  tgobject79248 Sup;
NCSTRING Name;
TY110172 Bgpixmapname;
tfontdescription91249* Fontdesc;
TY110176 Colorflags;
TY110274 Fg;
TY110274 Bg;
TY110274 Text;
TY110274 Base;
int Xthickness;
int Ythickness;
void* Rcproperties;
tgslist77382* Rcstylelists;
tgslist77382* Iconfactories;
NI16 Rcstyleflag0;
};
struct tgslist77382 {
void* Data;
tgslist77382* Next;
};
struct tvisual96350 {
  tgobject79248 Sup;
NU8 Thetype;
int Depth;
NU8 Byteorder;
int Colormapsize;
int Bitsperrgb;
NI32 Redmask;
int Redshift;
int Redprec;
NI32 Greenmask;
int Greenshift;
int Greenprec;
NI32 Bluemask;
int Blueshift;
int Blueprec;
tscreen96302* Screen;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP137, "libgtk-x11-2.0.so", 17);
STRING_LITERAL(TMP138, "libgtk-x11-2.0.so.0", 19);
STRING_LITERAL(TMP139, "libgtk-x11-2.0.so(|.0)", 22);
static void* TMP136;
TY115755 Dl_115754;
TY113076 Dl_113075;
TY122835 Dl_122834;
TY122827 Dl_122826;
extern TFrame* frameptr_11825;
TY114325 Dl_114324;
TY117510 Dl_117509;
TY117676 Dl_117675;
TY115519 Dl_115518;
TY113887 Dl_113886;
TY113896 Dl_113895;
TY137405 Dl_137404;
TY122824 Dl_122823;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_11825;
	frameptr_11825 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_11825 = (*frameptr_11825).prev;
}
N_NIMCALL(void, nimrodinit_141510)(void) {
	TY141512 cmdLine;
	int cmdCount;
	nimfr("nimrod_init", "gtk2.nim")
	memset((void*)cmdLine, 0, sizeof(cmdLine));
	cmdCount = 0;
	nimln(17064, "gtk2.nim");
	Dl_122826(((void*) (cmdLine)), ((void*) (&cmdCount)));	popFrame();
}
N_NIMCALL(NI, signalconnect_137423)(tobject106409* anobject, NCSTRING name, tsignalfunc106425 fun, void* funcdata) {
	NI result;
	nimfr("signal_connect", "gtk2.nim")
	result = 0;
	nimln(14691, "gtk2.nim");
	result = Dl_137404(anobject, name, fun, NIM_NIL, funcdata, NIM_NIL, 0, 0);
	popFrame();
	return result;
}
N_NIMCALL(tsignalfunc106425, signalfunc_112857)(void* f) {
	tsignalfunc106425 result;
	nimfr("SIGNAL_FUNC", "gtk2.nim")
	result = 0;
	nimln(10896, "gtk2.nim");
	result = ((tsignalfunc106425) (f));
	popFrame();
	return result;
}N_NOINLINE(void, gtkgtk2Init)(void) {
	nimfr("gtk2", "gtk2.nim")
	popFrame();
}

N_NOINLINE(void, gtkgtk2DatInit)(void) {
if (!((TMP136 = nimLoadLibrary((NimStringDesc*) &TMP137))
||(TMP136 = nimLoadLibrary((NimStringDesc*) &TMP138))
)) nimLoadLibraryError((NimStringDesc*) &TMP139);
	Dl_115754 = (TY115755) nimGetProcAddr(TMP136, "gtk_button_new_with_label");
	Dl_113075 = (TY113076) nimGetProcAddr(TMP136, "gtk_widget_show");
	Dl_122834 = (TY122835) nimGetProcAddr(TMP136, "gtk_main_quit");
	Dl_122826 = (TY122827) nimGetProcAddr(TMP136, "gtk_init");
	Dl_114324 = (TY114325) nimGetProcAddr(TMP136, "gtk_window_new");
	Dl_117509 = (TY117510) nimGetProcAddr(TMP136, "gtk_vbox_new");
	Dl_117675 = (TY117676) nimGetProcAddr(TMP136, "gtk_hbox_new");
	Dl_115518 = (TY115519) nimGetProcAddr(TMP136, "gtk_box_pack_start");
	Dl_113886 = (TY113887) nimGetProcAddr(TMP136, "gtk_container_set_border_width");
	Dl_113895 = (TY113896) nimGetProcAddr(TMP136, "gtk_container_add");
	Dl_137404 = (TY137405) nimGetProcAddr(TMP136, "gtk_signal_connect_full");
	Dl_122823 = (TY122824) nimGetProcAddr(TMP136, "gtk_main");
}

