/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rahul/projects/Nimrod/lib -o /home/rahul/musings/nimrod/gtk/nimcache/gtk_ex2.o /home/rahul/musings/nimrod/gtk/nimcache/gtk_ex2.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct twidget106465 twidget106465;
typedef struct twindow106531 twindow106531;
typedef struct tbutton106649 tbutton106649;
typedef struct tcontainer106511 tcontainer106511;
typedef struct tobject106409 tobject106409;
typedef struct tgobject79248 tgobject79248;
typedef struct tgtypeinstance77360 tgtypeinstance77360;
typedef struct tgtypeclass77356 tgtypeclass77356;
typedef struct tstyle107133 tstyle107133;
typedef struct trequisition106463 trequisition106463;
typedef struct tallocation96330 tallocation96330;
typedef struct twindow96224 twindow96224;
typedef struct tbin106519 tbin106519;
typedef struct twindowgroup106537 twindowgroup106537;
typedef struct tscreen96302 tscreen96302;
typedef struct tcolor96218 tcolor96218;
typedef struct tfontdescription91249 tfontdescription91249;
typedef struct tgc96280 tgc96280;
typedef struct tcolormap96356 tcolormap96356;
typedef struct tfont96244 tfont96244;
typedef struct trcstyle107115 trcstyle107115;
typedef struct tgslist77382 tgslist77382;
typedef struct tvisual96350 tvisual96350;
typedef N_CDECL_PTR(void, TY122835) (void);
typedef N_CDECL_PTR(twindow106531*, TY114325) (NI32 thetype);
typedef N_CDECL_PTR(tbutton106649*, TY115755) (NCSTRING label);
typedef N_CDECL_PTR(void, TY113887) (tcontainer106511* container, int borderwidth);
typedef N_CDECL_PTR(void, TY113896) (tcontainer106511* container, twidget106465* widget);
typedef N_CDECL_PTR(void, tsignalfunc106425) (void* para1);
typedef N_CDECL_PTR(void, TY113076) (twidget106465* widget);
typedef N_CDECL_PTR(void, TY122824) (void);
struct tgtypeinstance77360 {
tgtypeclass77356* Gclass;
};
struct tgobject79248 {
tgtypeinstance77360 Gtypeinstance;
int Refcount;
void* Qdata;
};
struct tobject106409 {
  tgobject79248 Sup;
NI32 Flags;
};
struct trequisition106463 {
int Width;
int Height;
};
struct tallocation96330 {
int X;
int Y;
int Width;
int Height;
};
struct twidget106465 {
  tobject106409 Sup;
NI16 Privateflags;
NI8 State;
NI8 Savedstate;
NCSTRING Name;
tstyle107133* Style;
trequisition106463 Requisition;
tallocation96330 Allocation;
twindow96224* Window;
twidget106465* Parent;
};
struct tcontainer106511 {
  twidget106465 Sup;
twidget106465* Focuschild;
NI32 Containerflag0;
};
struct tbin106519 {
  tcontainer106511 Sup;
twidget106465* Child;
};
struct twindow106531 {
  tbin106519 Sup;
NCSTRING Title;
NCSTRING Wmclassname;
NCSTRING Wmclassclass;
NCSTRING Wmrole;
twidget106465* Focuswidget;
twidget106465* Defaultwidget;
twindow106531* Transientparent;
void* Geometryinfo;
twindow96224* Frame;
twindowgroup106537* Group;
NI16 Configurerequestcount;
NI32 Windowflag0;
int Frameleft;
int Frametop;
int Frameright;
int Framebottom;
int Keyschangedhandler;
int Mnemonicmodifier;
tscreen96302* Screen;
};
struct tbutton106649 {
  tbin106519 Sup;
twindow96224* Eventwindow;
NCSTRING Labeltext;
int Activatetimeout;
NI16 Buttonflag0;
};
struct tgtypeclass77356 {
NI Gtype;
};
struct tcolor96218 {
NI32 Pixel;
NI16 Red;
NI16 Green;
NI16 Blue;
};
typedef tcolor96218 TY110274[5];
typedef tgc96280* TY110303[5];
typedef twindow96224* TY110329[5];
struct tstyle107133 {
  tgobject79248 Sup;
TY110274 Fg;
TY110274 Bg;
TY110274 Light;
TY110274 Dark;
TY110274 Mid;
TY110274 Text;
TY110274 Base;
TY110274 Textaa;
tcolor96218 Black;
tcolor96218 White;
tfontdescription91249* Fontdesc;
int Xthickness;
int Ythickness;
TY110303 Fggc;
TY110303 Bggc;
TY110303 Lightgc;
TY110303 Darkgc;
TY110303 Midgc;
TY110303 Textgc;
TY110303 Basegc;
TY110303 Textaagc;
tgc96280* Blackgc;
tgc96280* Whitegc;
TY110329 Bgpixmap;
int Attachcount;
int Depth;
tcolormap96356* Colormap;
tfont96244* Privatefont;
tfontdescription91249* Privatefontdesc;
trcstyle107115* Rcstyle;
tgslist77382* Styles;
void* Propertycache;
tgslist77382* Iconfactories;
};
struct twindow96224 {
  tgobject79248 Sup;
};
struct twindowgroup106537 {
  tgobject79248 Sup;
tgslist77382* Grabs;
};
struct tscreen96302 {
  tgobject79248 Sup;
};
struct tfontdescription91249 {
char dummy;
};
struct tgc96280 {
  tgobject79248 Sup;
int Clipxorigin;
int Clipyorigin;
int Tsxorigin;
int Tsyorigin;
tcolormap96356* Colormap;
};
struct tcolormap96356 {
  tgobject79248 Sup;
int Size;
tcolor96218* Colors;
tvisual96350* Visual;
void* Windowingdata;
tscreen96302* Screen;
};
struct tfont96244 {
NU8 Type;
int Ascent;
int Descent;
};
typedef NCSTRING TY110172[5];
typedef NI32 TY110176[5];
struct trcstyle107115 {
  tgobject79248 Sup;
NCSTRING Name;
TY110172 Bgpixmapname;
tfontdescription91249* Fontdesc;
TY110176 Colorflags;
TY110274 Fg;
TY110274 Bg;
TY110274 Text;
TY110274 Base;
int Xthickness;
int Ythickness;
void* Rcproperties;
tgslist77382* Rcstylelists;
tgslist77382* Iconfactories;
NI16 Rcstyleflag0;
};
struct tgslist77382 {
void* Data;
tgslist77382* Next;
};
struct tvisual96350 {
  tgobject79248 Sup;
NU8 Thetype;
int Depth;
NU8 Byteorder;
int Colormapsize;
int Bitsperrgb;
NI32 Redmask;
int Redshift;
int Redprec;
NI32 Greenmask;
int Greenshift;
int Greenprec;
NI32 Bluemask;
int Blueshift;
int Blueprec;
tscreen96302* Screen;
};
N_CDECL(void, destroy_142002)(twidget106465* widget, void** data);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, nimrodinit_141510)(void);
N_NIMCALL(NI, signalconnect_137423)(tobject106409* anobject, NCSTRING name, tsignalfunc106425 fun, void* funcdata);
N_NIMCALL(tsignalfunc106425, signalfunc_112857)(void* f);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, gtkglib2Init)(void);
N_NOINLINE(void, gtkglib2DatInit)(void);
N_NOINLINE(void, gtkatkInit)(void);
N_NOINLINE(void, gtkatkDatInit)(void);
N_NOINLINE(void, gtkpangoInit)(void);
N_NOINLINE(void, gtkpangoDatInit)(void);
N_NOINLINE(void, gtkgdk2pixbufInit)(void);
N_NOINLINE(void, gtkgdk2pixbufDatInit)(void);
N_NOINLINE(void, gtkgdk2Init)(void);
N_NOINLINE(void, gtkgdk2DatInit)(void);
N_NOINLINE(void, gtkgtk2Init)(void);
N_NOINLINE(void, gtkgtk2DatInit)(void);
N_NOINLINE(void, ex2Init)(void);
N_NOINLINE(void, ex2DatInit)(void);
extern TY122835 Dl_122834;
extern TFrame* frameptr_11825;
twidget106465* window_142008;
twidget106465* button_142009;
extern TY114325 Dl_114324;
extern TY115755 Dl_115754;
extern TY113887 Dl_113886;
extern TY113896 Dl_113895;
extern TY113076 Dl_113075;
extern TY122824 Dl_122823;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_11825;
	frameptr_11825 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_11825 = (*frameptr_11825).prev;
}
N_CDECL(void, destroy_142002)(twidget106465* widget, void** data) {
	nimfr("destroy", "ex2.nim")
	nimln(5, "ex2.nim");
	Dl_122834();	popFrame();
}
static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);}int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	systemDatInit();
	gtkglib2DatInit();
	gtkatkDatInit();
	gtkpangoDatInit();
	gtkgdk2pixbufDatInit();
	gtkgdk2DatInit();
	gtkgtk2DatInit();
	ex2DatInit();
	initStackBottom();
	systemInit();
	gtkglib2Init();
	gtkatkInit();
	gtkpangoInit();
	gtkgdk2pixbufInit();
	gtkgdk2Init();
	gtkgtk2Init();
	ex2Init();
}
int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}
N_NOINLINE(void, ex2Init)(void) {
	twindow106531* LOC1;
	tbutton106649* LOC2;
	tsignalfunc106425 LOC3;
	NI LOC4;
	nimfr("ex2", "ex2.nim")
	nimln(11, "ex2.nim");
	nimrodinit_141510();	nimln(12, "ex2.nim");
	nimln(12, "ex2.nim");
	LOC1 = 0;
	LOC1 = Dl_114324(((NI32) 0));
	window_142008 = &LOC1->Sup.Sup.Sup;
	nimln(13, "ex2.nim");
	nimln(13, "ex2.nim");
	LOC2 = 0;
	LOC2 = Dl_115754("Click me");
	button_142009 = &LOC2->Sup.Sup.Sup;
	nimln(14, "ex2.nim");
	Dl_113886(((tcontainer106511*) (window_142008)), ((int) 5));	nimln(15, "ex2.nim");
	Dl_113895(((tcontainer106511*) (window_142008)), button_142009);	nimln(16, "ex2.nim");
	nimln(16, "ex2.nim");
	nimln(16, "ex2.nim");
	LOC3 = 0;
	LOC3 = signalfunc_112857(destroy_142002);
	LOC4 = 0;
	LOC4 = signalconnect_137423(&window_142008->Sup, "destroy", LOC3, NIM_NIL);
	nimln(17, "ex2.nim");
	Dl_113075(button_142009);	nimln(18, "ex2.nim");
	Dl_113075(window_142008);	nimln(19, "ex2.nim");
	Dl_122823();	popFrame();
}

N_NOINLINE(void, ex2DatInit)(void) {
}

