/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rahul/projects/Nimrod/lib -o /home/rahul/musings/nimrod/gtk/nimcache/gtk_ex3.o /home/rahul/musings/nimrod/gtk/nimcache/gtk_ex3.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct twidget106465 twidget106465;
typedef struct tbutton106649 tbutton106649;
typedef struct twindow106531 twindow106531;
typedef struct tvbox106843 tvbox106843;
typedef struct thbox106871 thbox106871;
typedef struct tbox106629 tbox106629;
typedef struct tcontainer106511 tcontainer106511;
typedef struct tobject106409 tobject106409;
typedef struct tgobject79248 tgobject79248;
typedef struct tgtypeinstance77360 tgtypeinstance77360;
typedef struct tgtypeclass77356 tgtypeclass77356;
typedef struct tstyle107133 tstyle107133;
typedef struct trequisition106463 trequisition106463;
typedef struct tallocation96330 tallocation96330;
typedef struct twindow96224 twindow96224;
typedef struct tbin106519 tbin106519;
typedef struct twindowgroup106537 twindowgroup106537;
typedef struct tscreen96302 tscreen96302;
typedef struct tglist77386 tglist77386;
typedef struct tcolor96218 tcolor96218;
typedef struct tfontdescription91249 tfontdescription91249;
typedef struct tgc96280 tgc96280;
typedef struct tcolormap96356 tcolormap96356;
typedef struct tfont96244 tfont96244;
typedef struct trcstyle107115 trcstyle107115;
typedef struct tgslist77382 tgslist77382;
typedef struct tvisual96350 tvisual96350;
typedef N_CDECL_PTR(tbutton106649*, TY115755) (NCSTRING label);
typedef N_CDECL_PTR(void, TY113076) (twidget106465* widget);
typedef N_CDECL_PTR(void, TY122835) (void);
typedef N_CDECL_PTR(twindow106531*, TY114325) (NI32 thetype);
typedef N_CDECL_PTR(tvbox106843*, TY117510) (int homogeneous, int spacing);
typedef N_CDECL_PTR(thbox106871*, TY117676) (int homogeneous, int spacing);
typedef N_CDECL_PTR(void, TY115519) (tbox106629* box, twidget106465* child, int expand, int fill, int padding);
typedef N_CDECL_PTR(void, TY113887) (tcontainer106511* container, int borderwidth);
typedef N_CDECL_PTR(void, TY113896) (tcontainer106511* container, twidget106465* widget);
typedef N_CDECL_PTR(void, tsignalfunc106425) (void* para1);
typedef N_CDECL_PTR(void, TY122824) (void);
struct tgtypeinstance77360 {
tgtypeclass77356* Gclass;
};
struct tgobject79248 {
tgtypeinstance77360 Gtypeinstance;
int Refcount;
void* Qdata;
};
struct tobject106409 {
  tgobject79248 Sup;
NI32 Flags;
};
struct trequisition106463 {
int Width;
int Height;
};
struct tallocation96330 {
int X;
int Y;
int Width;
int Height;
};
struct twidget106465 {
  tobject106409 Sup;
NI16 Privateflags;
NI8 State;
NI8 Savedstate;
NCSTRING Name;
tstyle107133* Style;
trequisition106463 Requisition;
tallocation96330 Allocation;
twindow96224* Window;
twidget106465* Parent;
};
struct tcontainer106511 {
  twidget106465 Sup;
twidget106465* Focuschild;
NI32 Containerflag0;
};
struct tbin106519 {
  tcontainer106511 Sup;
twidget106465* Child;
};
struct tbutton106649 {
  tbin106519 Sup;
twindow96224* Eventwindow;
NCSTRING Labeltext;
int Activatetimeout;
NI16 Buttonflag0;
};
struct twindow106531 {
  tbin106519 Sup;
NCSTRING Title;
NCSTRING Wmclassname;
NCSTRING Wmclassclass;
NCSTRING Wmrole;
twidget106465* Focuswidget;
twidget106465* Defaultwidget;
twindow106531* Transientparent;
void* Geometryinfo;
twindow96224* Frame;
twindowgroup106537* Group;
NI16 Configurerequestcount;
NI32 Windowflag0;
int Frameleft;
int Frametop;
int Frameright;
int Framebottom;
int Keyschangedhandler;
int Mnemonicmodifier;
tscreen96302* Screen;
};
struct tbox106629 {
  tcontainer106511 Sup;
tglist77386* Children;
NI16 Spacing;
NI16 Boxflag0;
};
struct tvbox106843 {
  tbox106629 Sup;
};
struct thbox106871 {
  tbox106629 Sup;
};
struct tgtypeclass77356 {
NI Gtype;
};
struct tcolor96218 {
NI32 Pixel;
NI16 Red;
NI16 Green;
NI16 Blue;
};
typedef tcolor96218 TY110274[5];
typedef tgc96280* TY110303[5];
typedef twindow96224* TY110329[5];
struct tstyle107133 {
  tgobject79248 Sup;
TY110274 Fg;
TY110274 Bg;
TY110274 Light;
TY110274 Dark;
TY110274 Mid;
TY110274 Text;
TY110274 Base;
TY110274 Textaa;
tcolor96218 Black;
tcolor96218 White;
tfontdescription91249* Fontdesc;
int Xthickness;
int Ythickness;
TY110303 Fggc;
TY110303 Bggc;
TY110303 Lightgc;
TY110303 Darkgc;
TY110303 Midgc;
TY110303 Textgc;
TY110303 Basegc;
TY110303 Textaagc;
tgc96280* Blackgc;
tgc96280* Whitegc;
TY110329 Bgpixmap;
int Attachcount;
int Depth;
tcolormap96356* Colormap;
tfont96244* Privatefont;
tfontdescription91249* Privatefontdesc;
trcstyle107115* Rcstyle;
tgslist77382* Styles;
void* Propertycache;
tgslist77382* Iconfactories;
};
struct twindow96224 {
  tgobject79248 Sup;
};
struct twindowgroup106537 {
  tgobject79248 Sup;
tgslist77382* Grabs;
};
struct tscreen96302 {
  tgobject79248 Sup;
};
struct tglist77386 {
void* Data;
tglist77386* Next;
tglist77386* Prev;
};
struct tfontdescription91249 {
char dummy;
};
struct tgc96280 {
  tgobject79248 Sup;
int Clipxorigin;
int Clipyorigin;
int Tsxorigin;
int Tsyorigin;
tcolormap96356* Colormap;
};
struct tcolormap96356 {
  tgobject79248 Sup;
int Size;
tcolor96218* Colors;
tvisual96350* Visual;
void* Windowingdata;
tscreen96302* Screen;
};
struct tfont96244 {
NU8 Type;
int Ascent;
int Descent;
};
typedef NCSTRING TY110172[5];
typedef NI32 TY110176[5];
struct trcstyle107115 {
  tgobject79248 Sup;
NCSTRING Name;
TY110172 Bgpixmapname;
tfontdescription91249* Fontdesc;
TY110176 Colorflags;
TY110274 Fg;
TY110274 Bg;
TY110274 Text;
TY110274 Base;
int Xthickness;
int Ythickness;
void* Rcproperties;
tgslist77382* Rcstylelists;
tgslist77382* Iconfactories;
NI16 Rcstyleflag0;
};
struct tgslist77382 {
void* Data;
tgslist77382* Next;
};
struct tvisual96350 {
  tgobject79248 Sup;
NU8 Thetype;
int Depth;
NU8 Byteorder;
int Colormapsize;
int Bitsperrgb;
NI32 Redmask;
int Redshift;
int Redprec;
NI32 Greenmask;
int Greenshift;
int Greenprec;
NI32 Bluemask;
int Blueshift;
int Blueprec;
tscreen96302* Screen;
};
N_NIMCALL(twidget106465*, newbutton_142002)(NCSTRING alabel);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_CDECL(void, destroy_142008)(twidget106465* widget, void** data);
N_NIMCALL(void, nimrodinit_141510)(void);
N_NIMCALL(int, gbool_77497)(NIM_BOOL nimbool);
N_NIMCALL(NI, signalconnect_137423)(tobject106409* anobject, NCSTRING name, tsignalfunc106425 fun, void* funcdata);
N_NIMCALL(tsignalfunc106425, signalfunc_112857)(void* f);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, gtkglib2Init)(void);
N_NOINLINE(void, gtkglib2DatInit)(void);
N_NOINLINE(void, gtkatkInit)(void);
N_NOINLINE(void, gtkatkDatInit)(void);
N_NOINLINE(void, gtkpangoInit)(void);
N_NOINLINE(void, gtkpangoDatInit)(void);
N_NOINLINE(void, gtkgdk2pixbufInit)(void);
N_NOINLINE(void, gtkgdk2pixbufDatInit)(void);
N_NOINLINE(void, gtkgdk2Init)(void);
N_NOINLINE(void, gtkgdk2DatInit)(void);
N_NOINLINE(void, gtkgtk2Init)(void);
N_NOINLINE(void, gtkgtk2DatInit)(void);
N_NOINLINE(void, ex3Init)(void);
N_NOINLINE(void, ex3DatInit)(void);
extern TY115755 Dl_115754;
extern TY113076 Dl_113075;
extern TFrame* frameptr_11825;
extern TY122835 Dl_122834;
twindow106531* window_142015;
extern TY114325 Dl_114324;
tvbox106843* totalbox_142017;
extern TY117510 Dl_117509;
thbox106871* hbox_142020;
extern TY117676 Dl_117675;
tvbox106843* vbox_142023;
extern TY115519 Dl_115518;
extern TY113887 Dl_113886;
extern TY113896 Dl_113895;
extern TY122824 Dl_122823;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_11825;
	frameptr_11825 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_11825 = (*frameptr_11825).prev;
}
N_NIMCALL(twidget106465*, newbutton_142002)(NCSTRING alabel) {
	twidget106465* result;
	tbutton106649* LOC1;
	nimfr("newbutton", "ex3.nim")
	result = 0;
	nimln(5, "ex3.nim");
	nimln(5, "ex3.nim");
	LOC1 = 0;
	LOC1 = Dl_115754(alabel);
	result = &LOC1->Sup.Sup.Sup;
	nimln(6, "ex3.nim");
	Dl_113075(result);	popFrame();
	return result;
}
N_CDECL(void, destroy_142008)(twidget106465* widget, void** data) {
	nimfr("destroy", "ex3.nim")
	nimln(9, "ex3.nim");
	Dl_122834();	popFrame();
}
static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);}int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	systemDatInit();
	gtkglib2DatInit();
	gtkatkDatInit();
	gtkpangoDatInit();
	gtkgdk2pixbufDatInit();
	gtkgdk2DatInit();
	gtkgtk2DatInit();
	ex3DatInit();
	initStackBottom();
	systemInit();
	gtkglib2Init();
	gtkatkInit();
	gtkpangoInit();
	gtkgdk2pixbufInit();
	gtkgdk2Init();
	gtkgtk2Init();
	ex3Init();
}
int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}
N_NOINLINE(void, ex3Init)(void) {
	int LOC1;
	int LOC2;
	int LOC3;
	int LOC4;
	int LOC5;
	int LOC6;
	int LOC7;
	twidget106465* LOC8;
	int LOC9;
	int LOC10;
	twidget106465* LOC11;
	int LOC12;
	int LOC13;
	twidget106465* LOC14;
	int LOC15;
	int LOC16;
	twidget106465* LOC17;
	int LOC18;
	int LOC19;
	twidget106465* LOC20;
	int LOC21;
	int LOC22;
	twidget106465* LOC23;
	int LOC24;
	int LOC25;
	tsignalfunc106425 LOC26;
	NI LOC27;
	nimfr("ex3", "ex3.nim")
	nimln(11, "ex3.nim");
	nimrodinit_141510();	nimln(12, "ex3.nim");
	window_142015 = Dl_114324(((NI32) 0));
	nimln(13, "ex3.nim");
	nimln(13, "ex3.nim");
	LOC1 = 0;
	LOC1 = gbool_77497(NIM_TRUE);
	totalbox_142017 = Dl_117509(LOC1, ((int) 10));
	nimln(14, "ex3.nim");
	Dl_113075(&totalbox_142017->Sup.Sup.Sup);	nimln(15, "ex3.nim");
	nimln(15, "ex3.nim");
	LOC2 = 0;
	LOC2 = gbool_77497(NIM_FALSE);
	hbox_142020 = Dl_117675(LOC2, ((int) 5));
	nimln(16, "ex3.nim");
	Dl_113075(&hbox_142020->Sup.Sup.Sup);	nimln(17, "ex3.nim");
	nimln(17, "ex3.nim");
	LOC3 = 0;
	LOC3 = gbool_77497(NIM_TRUE);
	vbox_142023 = Dl_117509(LOC3, ((int) 5));
	nimln(18, "ex3.nim");
	Dl_113075(&vbox_142023->Sup.Sup.Sup);	nimln(19, "ex3.nim");
	nimln(19, "ex3.nim");
	LOC4 = 0;
	LOC4 = gbool_77497(NIM_TRUE);
	nimln(19, "ex3.nim");
	LOC5 = 0;
	LOC5 = gbool_77497(NIM_TRUE);
	Dl_115518(&totalbox_142017->Sup, &hbox_142020->Sup.Sup.Sup, LOC4, LOC5, ((int) 0));	nimln(20, "ex3.nim");
	nimln(20, "ex3.nim");
	LOC6 = 0;
	LOC6 = gbool_77497(NIM_TRUE);
	nimln(20, "ex3.nim");
	LOC7 = 0;
	LOC7 = gbool_77497(NIM_TRUE);
	Dl_115518(&totalbox_142017->Sup, &vbox_142023->Sup.Sup.Sup, LOC6, LOC7, ((int) 0));	nimln(22, "ex3.nim");
	nimln(22, "ex3.nim");
	LOC8 = 0;
	LOC8 = newbutton_142002("Button 1");
	nimln(22, "ex3.nim");
	LOC9 = 0;
	LOC9 = gbool_77497(NIM_FALSE);
	nimln(22, "ex3.nim");
	LOC10 = 0;
	LOC10 = gbool_77497(NIM_FALSE);
	Dl_115518(&hbox_142020->Sup, LOC8, LOC9, LOC10, ((int) 0));	nimln(23, "ex3.nim");
	nimln(23, "ex3.nim");
	LOC11 = 0;
	LOC11 = newbutton_142002("Button 2");
	nimln(23, "ex3.nim");
	LOC12 = 0;
	LOC12 = gbool_77497(NIM_FALSE);
	nimln(23, "ex3.nim");
	LOC13 = 0;
	LOC13 = gbool_77497(NIM_FALSE);
	Dl_115518(&hbox_142020->Sup, LOC11, LOC12, LOC13, ((int) 0));	nimln(24, "ex3.nim");
	nimln(24, "ex3.nim");
	LOC14 = 0;
	LOC14 = newbutton_142002("Button 3");
	nimln(24, "ex3.nim");
	LOC15 = 0;
	LOC15 = gbool_77497(NIM_FALSE);
	nimln(24, "ex3.nim");
	LOC16 = 0;
	LOC16 = gbool_77497(NIM_FALSE);
	Dl_115518(&hbox_142020->Sup, LOC14, LOC15, LOC16, ((int) 0));	nimln(25, "ex3.nim");
	nimln(25, "ex3.nim");
	LOC17 = 0;
	LOC17 = newbutton_142002("Button A");
	nimln(25, "ex3.nim");
	LOC18 = 0;
	LOC18 = gbool_77497(NIM_TRUE);
	nimln(25, "ex3.nim");
	LOC19 = 0;
	LOC19 = gbool_77497(NIM_TRUE);
	Dl_115518(&vbox_142023->Sup, LOC17, LOC18, LOC19, ((int) 0));	nimln(26, "ex3.nim");
	nimln(26, "ex3.nim");
	LOC20 = 0;
	LOC20 = newbutton_142002("Button B");
	nimln(26, "ex3.nim");
	LOC21 = 0;
	LOC21 = gbool_77497(NIM_TRUE);
	nimln(26, "ex3.nim");
	LOC22 = 0;
	LOC22 = gbool_77497(NIM_TRUE);
	Dl_115518(&vbox_142023->Sup, LOC20, LOC21, LOC22, ((int) 0));	nimln(27, "ex3.nim");
	nimln(27, "ex3.nim");
	LOC23 = 0;
	LOC23 = newbutton_142002("Button C");
	nimln(27, "ex3.nim");
	LOC24 = 0;
	LOC24 = gbool_77497(NIM_TRUE);
	nimln(27, "ex3.nim");
	LOC25 = 0;
	LOC25 = gbool_77497(NIM_TRUE);
	Dl_115518(&vbox_142023->Sup, LOC23, LOC24, LOC25, ((int) 0));	nimln(28, "ex3.nim");
	Dl_113886(&window_142015->Sup.Sup, ((int) 5));	nimln(29, "ex3.nim");
	Dl_113895(&window_142015->Sup.Sup, &totalbox_142017->Sup.Sup.Sup);	nimln(30, "ex3.nim");
	nimln(30, "ex3.nim");
	nimln(30, "ex3.nim");
	LOC26 = 0;
	LOC26 = signalfunc_112857(destroy_142008);
	LOC27 = 0;
	LOC27 = signalconnect_137423(&window_142015->Sup.Sup.Sup.Sup, "destroy", LOC26, NIM_NIL);
	nimln(31, "ex3.nim");
	Dl_113075(&window_142015->Sup.Sup.Sup);	nimln(32, "ex3.nim");
	Dl_122823();	popFrame();
}

N_NOINLINE(void, ex3DatInit)(void) {
}

