/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rahul/projects/Nimrod/lib -o /home/rahul/musings/nimrod/nimcache/gtk_gtk2.o /home/rahul/musings/nimrod/nimcache/gtk_gtk2.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct twindow108531 twindow108531;
typedef struct tobject108409 tobject108409;
typedef struct twidget108465 twidget108465;
typedef struct tbin108519 tbin108519;
typedef struct tcontainer108511 tcontainer108511;
typedef struct tgobject81248 tgobject81248;
typedef struct tgtypeinstance79360 tgtypeinstance79360;
typedef struct tgtypeclass79356 tgtypeclass79356;
typedef struct tstyle109133 tstyle109133;
typedef struct trequisition108463 trequisition108463;
typedef struct tallocation98330 tallocation98330;
typedef struct twindow98224 twindow98224;
typedef struct twindowgroup108537 twindowgroup108537;
typedef struct tscreen98302 tscreen98302;
typedef struct tcolor98218 tcolor98218;
typedef struct tfontdescription93249 tfontdescription93249;
typedef struct tgc98280 tgc98280;
typedef struct tcolormap98356 tcolormap98356;
typedef struct tfont98244 tfont98244;
typedef struct trcstyle109115 trcstyle109115;
typedef struct tgslist79382 tgslist79382;
typedef struct tvisual98350 tvisual98350;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_CDECL_PTR(void, TY124835) (void);
typedef NCSTRING TY143512[256];
typedef N_CDECL_PTR(void, TY124827) (void* argc, void* argv);
typedef N_CDECL_PTR(twindow108531*, TY116325) (NI32 thetype);
typedef N_CDECL_PTR(void, tsignalfunc108425) (void* para1);
typedef N_CDECL_PTR(NI, TY139405) (tobject108409* anobject, NCSTRING name, tsignalfunc108425 fun, void* unknown1, void* funcdata, void* unknown2, NI unknown3, NI unknown4);
typedef N_CDECL_PTR(void, TY115076) (twidget108465* widget);
typedef N_CDECL_PTR(void, TY124824) (void);
struct tgtypeinstance79360 {
tgtypeclass79356* Gclass;
};
struct tgobject81248 {
tgtypeinstance79360 Gtypeinstance;
int Refcount;
void* Qdata;
};
struct tobject108409 {
  tgobject81248 Sup;
NI32 Flags;
};
struct trequisition108463 {
int Width;
int Height;
};
struct tallocation98330 {
int X;
int Y;
int Width;
int Height;
};
struct twidget108465 {
  tobject108409 Sup;
NI16 Privateflags;
NI8 State;
NI8 Savedstate;
NCSTRING Name;
tstyle109133* Style;
trequisition108463 Requisition;
tallocation98330 Allocation;
twindow98224* Window;
twidget108465* Parent;
};
struct tcontainer108511 {
  twidget108465 Sup;
twidget108465* Focuschild;
NI32 Containerflag0;
};
struct tbin108519 {
  tcontainer108511 Sup;
twidget108465* Child;
};
struct twindow108531 {
  tbin108519 Sup;
NCSTRING Title;
NCSTRING Wmclassname;
NCSTRING Wmclassclass;
NCSTRING Wmrole;
twidget108465* Focuswidget;
twidget108465* Defaultwidget;
twindow108531* Transientparent;
void* Geometryinfo;
twindow98224* Frame;
twindowgroup108537* Group;
NI16 Configurerequestcount;
NI32 Windowflag0;
int Frameleft;
int Frametop;
int Frameright;
int Framebottom;
int Keyschangedhandler;
int Mnemonicmodifier;
tscreen98302* Screen;
};
struct tgtypeclass79356 {
NI Gtype;
};
struct tcolor98218 {
NI32 Pixel;
NI16 Red;
NI16 Green;
NI16 Blue;
};
typedef tcolor98218 TY112274[5];
typedef tgc98280* TY112303[5];
typedef twindow98224* TY112329[5];
struct tstyle109133 {
  tgobject81248 Sup;
TY112274 Fg;
TY112274 Bg;
TY112274 Light;
TY112274 Dark;
TY112274 Mid;
TY112274 Text;
TY112274 Base;
TY112274 Textaa;
tcolor98218 Black;
tcolor98218 White;
tfontdescription93249* Fontdesc;
int Xthickness;
int Ythickness;
TY112303 Fggc;
TY112303 Bggc;
TY112303 Lightgc;
TY112303 Darkgc;
TY112303 Midgc;
TY112303 Textgc;
TY112303 Basegc;
TY112303 Textaagc;
tgc98280* Blackgc;
tgc98280* Whitegc;
TY112329 Bgpixmap;
int Attachcount;
int Depth;
tcolormap98356* Colormap;
tfont98244* Privatefont;
tfontdescription93249* Privatefontdesc;
trcstyle109115* Rcstyle;
tgslist79382* Styles;
void* Propertycache;
tgslist79382* Iconfactories;
};
struct twindow98224 {
  tgobject81248 Sup;
};
struct twindowgroup108537 {
  tgobject81248 Sup;
tgslist79382* Grabs;
};
struct tscreen98302 {
  tgobject81248 Sup;
};
struct tfontdescription93249 {
char dummy;
};
struct tgc98280 {
  tgobject81248 Sup;
int Clipxorigin;
int Clipyorigin;
int Tsxorigin;
int Tsyorigin;
tcolormap98356* Colormap;
};
struct tcolormap98356 {
  tgobject81248 Sup;
int Size;
tcolor98218* Colors;
tvisual98350* Visual;
void* Windowingdata;
tscreen98302* Screen;
};
struct tfont98244 {
NU8 Type;
int Ascent;
int Descent;
};
typedef NCSTRING TY112172[5];
typedef NI32 TY112176[5];
struct trcstyle109115 {
  tgobject81248 Sup;
NCSTRING Name;
TY112172 Bgpixmapname;
tfontdescription93249* Fontdesc;
TY112176 Colorflags;
TY112274 Fg;
TY112274 Bg;
TY112274 Text;
TY112274 Base;
int Xthickness;
int Ythickness;
void* Rcproperties;
tgslist79382* Rcstylelists;
tgslist79382* Iconfactories;
NI16 Rcstyleflag0;
};
struct tgslist79382 {
void* Data;
tgslist79382* Next;
};
struct tvisual98350 {
  tgobject81248 Sup;
NU8 Thetype;
int Depth;
NU8 Byteorder;
int Colormapsize;
int Bitsperrgb;
NI32 Redmask;
int Redshift;
int Redprec;
NI32 Greenmask;
int Greenshift;
int Greenprec;
NI32 Bluemask;
int Blueshift;
int Blueprec;
tscreen98302* Screen;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
STRING_LITERAL(TMP151, "libgtk-x11-2.0.so", 17);
STRING_LITERAL(TMP152, "libgtk-x11-2.0.so.0", 19);
STRING_LITERAL(TMP153, "libgtk-x11-2.0.so(|.0)", 22);
static void* TMP150;
TY124835 Dl_124834;
TY124827 Dl_124826;
extern TFrame* frameptr_11825;
TY116325 Dl_116324;
TY139405 Dl_139404;
TY115076 Dl_115075;
TY124824 Dl_124823;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_11825;
	frameptr_11825 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_11825 = (*frameptr_11825).prev;
}
N_NIMCALL(void, nimrodinit_143510)(void) {
	TY143512 cmdLine;
	int cmdCount;
	nimfr("nimrod_init", "gtk2.nim")
	memset((void*)cmdLine, 0, sizeof(cmdLine));
	cmdCount = 0;
	nimln(17064, "gtk2.nim");
	Dl_124826(((void*) (cmdLine)), ((void*) (&cmdCount)));	popFrame();
}
N_NIMCALL(NI, signalconnect_139423)(tobject108409* anobject, NCSTRING name, tsignalfunc108425 fun, void* funcdata) {
	NI result;
	nimfr("signal_connect", "gtk2.nim")
	result = 0;
	nimln(14691, "gtk2.nim");
	result = Dl_139404(anobject, name, fun, NIM_NIL, funcdata, NIM_NIL, 0, 0);
	popFrame();
	return result;
}
N_NIMCALL(tsignalfunc108425, signalfunc_114857)(void* f) {
	tsignalfunc108425 result;
	nimfr("SIGNAL_FUNC", "gtk2.nim")
	result = 0;
	nimln(10896, "gtk2.nim");
	result = ((tsignalfunc108425) (f));
	popFrame();
	return result;
}N_NOINLINE(void, gtkgtk2Init)(void) {
	nimfr("gtk2", "gtk2.nim")
	popFrame();
}

N_NOINLINE(void, gtkgtk2DatInit)(void) {
if (!((TMP150 = nimLoadLibrary((NimStringDesc*) &TMP151))
||(TMP150 = nimLoadLibrary((NimStringDesc*) &TMP152))
)) nimLoadLibraryError((NimStringDesc*) &TMP153);
	Dl_124834 = (TY124835) nimGetProcAddr(TMP150, "gtk_main_quit");
	Dl_124826 = (TY124827) nimGetProcAddr(TMP150, "gtk_init");
	Dl_116324 = (TY116325) nimGetProcAddr(TMP150, "gtk_window_new");
	Dl_139404 = (TY139405) nimGetProcAddr(TMP150, "gtk_signal_connect_full");
	Dl_115075 = (TY115076) nimGetProcAddr(TMP150, "gtk_widget_show");
	Dl_124823 = (TY124824) nimGetProcAddr(TMP150, "gtk_main");
}

