/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rahul/projects/Nimrod/lib -o /home/rahul/musings/nimrod/nimcache/gtk_gdk2pixbuf.o /home/rahul/musings/nimrod/nimcache/gtk_gdk2pixbuf.c */
#define NIM_INTBITS 64
#include "nimbase.h"
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
extern TFrame* frameptr_11825;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_11825;
	frameptr_11825 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_11825 = (*frameptr_11825).prev;
}N_NOINLINE(void, gtkgdk2pixbufInit)(void) {
	nimfr("gdk2pixbuf", "gdk2pixbuf.nim")
	popFrame();
}

N_NOINLINE(void, gtkgdk2pixbufDatInit)(void) {
}

