/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rahul/projects/Nimrod/lib -o /home/rahul/musings/nimrod/nimcache/nimrod_multi.o /home/rahul/musings/nimrod/nimcache/nimrod_multi.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct tthing77003 tthing77003;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tunit77005 tunit77005;
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct tthing77003 {
  TNimObject Sup;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tunit77005 {
  tthing77003 Sup;
NI X;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(void, collide_77008)(tthing77003* a, tthing77003* b);
N_NIMCALL(void, quit_74829)(NimStringDesc* errormsg, NI errorcode);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, collide_77017)(tthing77003* a, tunit77005* b);
static N_INLINE(void, collide_77023)(tunit77005* a, tthing77003* b);
N_NIMCALL(void, collide_77014)(tthing77003* a, tthing77003* b);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, multiInit)(void);
N_NOINLINE(void, multiDatInit)(void);
STRING_LITERAL(TMP124, "To be overridden", 16);
STRING_LITERAL(TMP125, "1", 1);
STRING_LITERAL(TMP126, "2", 1);
extern TFrame* frameptr_11825;
tunit77005 a_77029;
extern TNimType NTI1009; /* TObject */
TNimType NTI77003; /* TThing */
TNimType NTI77005; /* TUnit */
extern TNimType NTI105; /* int */
tunit77005 b_77030;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_11825;
	frameptr_11825 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_11825 = (*frameptr_11825).prev;
}
static N_INLINE(void, collide_77008)(tthing77003* a, tthing77003* b) {
	nimfr("collide", "multi.nim")
	nimln(7, "multi.nim");
	quit_74829(((NimStringDesc*) &TMP124), 1);	popFrame();
}
static N_INLINE(void, collide_77017)(tthing77003* a, tunit77005* b) {
	nimfr("collide", "multi.nim")
	nimln(10, "multi.nim");
	printf("%s\012", (((NimStringDesc*) &TMP125))->data);
	popFrame();
}
static N_INLINE(void, collide_77023)(tunit77005* a, tthing77003* b) {
	nimfr("collide", "multi.nim")
	nimln(13, "multi.nim");
	printf("%s\012", (((NimStringDesc*) &TMP126))->data);
	popFrame();
}
N_NIMCALL(void, collide_77014)(tthing77003* a, tthing77003* b) {
	nimfr("collide", "multi.nim")
	nimln(6, "multi.nim");
	{
		nimln(6, "multi.nim");
		nimln(6, "multi.nim");
		nimln(6, "multi.nim");
		if (!(NIM_BOOL)(isObj((*a).Sup.m_type, (&NTI77005)) & isObj((*b).Sup.m_type, (&NTI77003)))) goto LA3;
		nimln(6, "multi.nim");
		chckObj((*a).Sup.m_type, (&NTI77005));
		collide_77023(&(*(tunit77005*) (a)), b);	}	goto LA1;
	LA3: ;
	{
		nimln(6, "multi.nim");
		nimln(6, "multi.nim");
		nimln(6, "multi.nim");
		if (!(NIM_BOOL)(isObj((*a).Sup.m_type, (&NTI77003)) & isObj((*b).Sup.m_type, (&NTI77005)))) goto LA6;
		nimln(6, "multi.nim");
		chckObj((*b).Sup.m_type, (&NTI77005));
		collide_77017(a, &(*(tunit77005*) (b)));	}	goto LA1;
	LA6: ;
	{
		nimln(6, "multi.nim");
		nimln(6, "multi.nim");
		nimln(6, "multi.nim");
		if (!(NIM_BOOL)(isObj((*a).Sup.m_type, (&NTI77003)) & isObj((*b).Sup.m_type, (&NTI77003)))) goto LA9;
		nimln(6, "multi.nim");
		collide_77008(a, b);	}	goto LA1;
	LA9: ;
	LA1: ;
	popFrame();
}
static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);}int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	systemDatInit();
	multiDatInit();
	initStackBottom();
	systemInit();
	multiInit();
}
int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}
N_NOINLINE(void, multiInit)(void) {
	nimfr("multi", "multi.nim")
	a_77029.Sup.Sup.m_type = (&NTI77005);
	b_77030.Sup.Sup.m_type = (&NTI77005);
	nimln(18, "multi.nim");
	collide_77014(&a_77029.Sup, &b_77030.Sup);	popFrame();
}

N_NOINLINE(void, multiDatInit)(void) {
static TNimNode TMP122[2];
NTI77003.size = sizeof(tthing77003);
NTI77003.kind = 17;
NTI77003.base = (&NTI1009);
NTI77003.flags = 3;
TMP122[0].len = 0; TMP122[0].kind = 2;
NTI77003.node = &TMP122[0];
NTI77005.size = sizeof(tunit77005);
NTI77005.kind = 17;
NTI77005.base = (&NTI77003);
NTI77005.flags = 3;
TMP122[1].kind = 1;
TMP122[1].offset = offsetof(tunit77005, X);
TMP122[1].typ = (&NTI105);
TMP122[1].name = "x";
NTI77005.node = &TMP122[1];
}

