/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rahul/projects/Nimrod/lib -o /home/rahul/musings/nimrod/nimcache/nimrod_tree.o /home/rahul/musings/nimrod/nimcache/nimrod_tree.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct tbinarytree77089 tbinarytree77089;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tcell38648 tcell38648;
typedef struct tcellseq38664 tcellseq38664;
typedef struct tgcheap40616 tgcheap40616;
typedef struct tcellset38660 tcellset38660;
typedef struct tpagedesc38656 tpagedesc38656;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21238 tsmallchunk21238;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21240 tbigchunk21240;
typedef struct tintset21215 tintset21215;
typedef struct ttrunk21211 ttrunk21211;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40614 tgcstat40614;
typedef struct TY77285 TY77285;
typedef struct tbasechunk21236 tbasechunk21236;
typedef struct tfreecell21228 tfreecell21228;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
struct tbinarytree77089 {
tbinarytree77089* Le;
tbinarytree77089* Ri;
NimStringDesc* Data;
};
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell38648 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38664 {
NI Len;
NI Cap;
tcell38648** D;
};
struct tcellset38660 {
NI Counter;
NI Max;
tpagedesc38656* Head;
tpagedesc38656** Data;
};
typedef tsmallchunk21238* TY22022[512];
typedef ttrunk21211* ttrunkbuckets21213[256];
struct tintset21215 {
ttrunkbuckets21213 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21240* Freechunkslist;
tintset21215 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40614 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40616 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38664 Zct;
tcellseq38664 Decstack;
tcellset38660 Cycleroots;
tcellseq38664 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40614 Stat;
};
typedef tbinarytree77089* TY77267[1];
typedef NimStringDesc* TY77370[1];
typedef NI TY21218[8];
struct tpagedesc38656 {
tpagedesc38656* Next;
NI Key;
TY21218 Bits;
};
struct tbasechunk21236 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21238 {
  tbasechunk21236 Sup;
tsmallchunk21238* Next;
tsmallchunk21238* Prev;
tfreecell21228* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21240 {
  tbasechunk21236 Sup;
tbigchunk21240* Next;
tbigchunk21240* Prev;
NI Align;
NF Data;
};
struct ttrunk21211 {
ttrunk21211* Next;
NI Key;
TY21218 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21228 {
tfreecell21228* Next;
NI Zerofield;
};
struct TY77285 {
  TGenericSeq Sup;
  tbinarytree77089* data[SEQ_DECL_SIZE];
};
N_NIMCALL(tbinarytree77089*, newnode_77114)(NimStringDesc* data);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP125)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tcell38648*, usrtocell_42039)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_43602)(tcell38648* c);
N_NOINLINE(void, addzct_42015)(tcellseq38664* s, tcell38648* c);
N_NIMCALL(void, add_77138)(tbinarytree77089** root, tbinarytree77089* n);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NI, cmp_2131)(NimStringDesc* x, NimStringDesc* y);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, add_77208)(tbinarytree77089** root, NimStringDesc* data);
static N_INLINE(tbinarytree77089*, pop_77282)(TY77285** s);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
static N_INLINE(void, writeln_77347)(FILE* f, NimStringDesc** x, NI xLen0);
N_NIMCALL(void, write_9259)(FILE* f, NimStringDesc* s);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, incrSeq)(TGenericSeq* seq, NI elemsize);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, treeInit)(void);
N_NOINLINE(void, treeDatInit)(void);
STRING_LITERAL(TMP126, "hello", 5);
STRING_LITERAL(TMP127, "world", 5);
STRING_LITERAL(TMP129, "\012", 1);
tbinarytree77089* root_77108;
TNimType NTI77089; /* TBinaryTree */
extern TNimType NTI142; /* string */
TNimType NTI77086; /* PBinaryTree */
extern TFrame* frameptr_11825;
extern tgcheap40616 gch_40644;
NimStringDesc* str_77342;
extern TNimType NTI77285; /* seq[PBinaryTree[string]] */
N_NIMCALL(void, TMP125)(void* p, NI op) {
	tbinarytree77089* a;
	a = (tbinarytree77089*)p;
	nimGCvisit((void*)(*a).Le, op);
	nimGCvisit((void*)(*a).Ri, op);
	nimGCvisit((void*)(*a).Data, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_11825;
	frameptr_11825 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_11825 = (*frameptr_11825).prev;
}
static N_INLINE(tcell38648*, usrtocell_42039)(void* usr) {
	tcell38648* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(116, "gc.nim");
	nimln(116, "gc.nim");
	nimln(116, "gc.nim");
	result = ((tcell38648*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38648))))));
	popFrame();
	return result;
}
static N_INLINE(void, rtladdzct_43602)(tcell38648* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(197, "gc.nim");
	addzct_42015(&gch_40644.Zct, c);	popFrame();
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tcell38648* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(231, "gc.nim");
	c = usrtocell_42039(p);
	nimln(233, "gc.nim");
	{
		nimln(165, "gc.nim");
		(*c).Refcount -= 8;
		nimln(166, "gc.nim");
		if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA3;
		nimln(234, "gc.nim");
		rtladdzct_43602(c);	}	LA3: ;
	popFrame();
}
N_NIMCALL(tbinarytree77089*, newnode_77114)(NimStringDesc* data) {
	tbinarytree77089* result;
	NimStringDesc* LOC1;
	nimfr("newNode", "tree.nim")
	result = 0;
	nimln(8, "tree.nim");
	result = (tbinarytree77089*) newObj((&NTI77086), sizeof(tbinarytree77089));
	nimln(9, "tree.nim");
	LOC1 = 0;
	LOC1 = (*result).Data; (*result).Data = copyStringRC1(data);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
	return result;
}
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(249, "gc.nim");
	{
		tcell38648* c;
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(250, "gc.nim");
		c = usrtocell_42039(src);
		nimln(167, "gc.nim");
		(*c).Refcount += 8;
	}	LA3: ;
	nimln(252, "gc.nim");
	{
		tcell38648* c;
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(253, "gc.nim");
		c = usrtocell_42039((*dest));
		nimln(254, "gc.nim");
		{
			nimln(165, "gc.nim");
			(*c).Refcount -= 8;
			nimln(166, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(255, "gc.nim");
			rtladdzct_43602(c);		}		LA11: ;
	}	LA7: ;
	nimln(256, "gc.nim");
	(*dest) = src;
	popFrame();
}
N_NIMCALL(void, add_77138)(tbinarytree77089** root, tbinarytree77089* n) {
	nimfr("add", "tree.nim")
	nimln(12, "tree.nim");
	{
		nimln(12, "tree.nim");
		if (!((*root) == NIM_NIL)) goto LA3;
		nimln(13, "tree.nim");
		unsureAsgnRef((void**) &(*root), n);
	}	goto LA1;
	LA3: ;
	{
		tbinarytree77089* it;
		nimln(15, "tree.nim");
		unsureAsgnRef((void**) &it, (*root));
		nimln(16, "tree.nim");
		while (1) {
			NI c;
			nimln(698, "system.nim");
			nimln(698, "system.nim");
			if (!!((it == NIM_NIL))) goto LA6;
			nimln(17, "tree.nim");
			c = cmp_2131((*it).Data, (*n).Data);
			nimln(18, "tree.nim");
			{
				nimln(18, "tree.nim");
				if (!(c < 0)) goto LA9;
				nimln(19, "tree.nim");
				{
					nimln(19, "tree.nim");
					if (!((*it).Le == NIM_NIL)) goto LA13;
					nimln(20, "tree.nim");
					asgnRefNoCycle((void**) &(*it).Le, n);
					nimln(21, "tree.nim");
					goto BeforeRet;
				}				goto LA11;
				LA13: ;
				{
					nimln(23, "tree.nim");
					{
						nimln(23, "tree.nim");
						if (!((*it).Ri == NIM_NIL)) goto LA18;
						nimln(24, "tree.nim");
						asgnRefNoCycle((void**) &(*it).Ri, n);
						nimln(25, "tree.nim");
						goto BeforeRet;
					}					LA18: ;
					nimln(26, "tree.nim");
					unsureAsgnRef((void**) &it, (*it).Ri);
				}				LA11: ;
			}			LA9: ;
		} LA6: ;
	}	LA1: ;
	BeforeRet: ;	popFrame();
}
N_NIMCALL(void, add_77208)(tbinarytree77089** root, NimStringDesc* data) {
	tbinarytree77089* LOC1;
	nimfr("add", "tree.nim")
	nimln(29, "tree.nim");
	nimln(29, "tree.nim");
	LOC1 = 0;
	LOC1 = newnode_77114(data);
	add_77138(root, LOC1);	popFrame();
}
static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}	LA5: ;
	raiseOverflow();	BeforeRet: ;	return result;
}
static N_INLINE(tbinarytree77089*, pop_77282)(TY77285** s) {
	tbinarytree77089* result;
	NI l;
	NI TMP128;
	nimfr("pop", "system.nim")
	result = 0;
	nimln(1533, "system.nim");
	nimln(1533, "system.nim");
	nimln(1533, "system.nim");
	TMP128 = subInt((*s)->Sup.len, 1);
	l = (NI64)(TMP128);
	nimln(1534, "system.nim");
	if ((NU)(l) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = (*s)->data[l];
	nimln(1535, "system.nim");
	(*s) = (TY77285*) setLengthSeq(&((*s))->Sup, sizeof(tbinarytree77089*), l);
	popFrame();
	return result;
}
static N_INLINE(void, writeln_77347)(FILE* f, NimStringDesc** x, NI xLen0) {
	NimStringDesc* i_77361;
	NI i_77367;
	nimfr("writeln", "sysio.nim")
	i_77361 = 0;
	nimln(1373, "system.nim");
	i_77367 = 0;
	nimln(1374, "system.nim");
	while (1) {
		nimln(1374, "system.nim");
		nimln(1374, "system.nim");
		if (!(i_77367 < xLen0)) goto LA1;
		nimln(1375, "system.nim");
		i_77361 = x[i_77367];
		nimln(159, "sysio.nim");
		write_9259(f, i_77361);		nimln(1376, "system.nim");
		i_77367 += 1;
	} LA1: ;
	nimln(160, "sysio.nim");
	write_9259(f, ((NimStringDesc*) &TMP129));	popFrame();
}
static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);}int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	systemDatInit();
	treeDatInit();
	initStackBottom();
	systemInit();
	treeInit();
}
int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}
N_NOINLINE(void, treeInit)(void) {
	tbinarytree77089* LOC1;
	TY77285* stack_77373;
	TY77267 LOC2;
	nimfr("tree", "tree.nim")
	nimln(42, "tree.nim");
	nimln(42, "tree.nim");
	LOC1 = 0;
	LOC1 = newnode_77114(((NimStringDesc*) &TMP126));
	add_77138(&root_77108, LOC1);	nimln(43, "tree.nim");
	add_77208(&root_77108, ((NimStringDesc*) &TMP127));	nimln(32, "tree.nim");
	nimln(32, "tree.nim");
	stack_77373 = (TY77285*) newSeq((&NTI77285), 1);
	memset((void*)LOC2, 0, sizeof(LOC2));
	LOC2[0] = root_77108;
	asgnRefNoCycle((void**) &stack_77373->data[0], LOC2[0]);
	nimln(33, "tree.nim");
	while (1) {
		tbinarytree77089* n_77375;
		nimln(706, "system.nim");
		nimln(33, "tree.nim");
		if (!(0 < stack_77373->Sup.len)) goto LA3;
		nimln(34, "tree.nim");
		n_77375 = pop_77282(&stack_77373);
		nimln(35, "tree.nim");
		while (1) {
			NimStringDesc* LOC5;
			TY77370 LOC6;
			nimln(698, "system.nim");
			nimln(698, "system.nim");
			if (!!((n_77375 == NIM_NIL))) goto LA4;
			nimln(36, "tree.nim");
			LOC5 = 0;
			LOC5 = str_77342; str_77342 = copyStringRC1((*n_77375).Data);
			if (LOC5) nimGCunrefNoCycle(LOC5);
			nimln(45, "tree.nim");
			memset((void*)LOC6, 0, sizeof(LOC6));
			nimln(45, "tree.nim");
			LOC6[0] = copyString(str_77342);
			writeln_77347(stdout, LOC6, 1);			nimln(37, "tree.nim");
			stack_77373 = (TY77285*) incrSeq(&(stack_77373)->Sup, sizeof(tbinarytree77089*));
			asgnRefNoCycle((void**) &stack_77373->data[stack_77373->Sup.len-1], (*n_77375).Ri);
			nimln(38, "tree.nim");
			n_77375 = (*n_77375).Le;
		} LA4: ;
	} LA3: ;
	popFrame();
}

N_NOINLINE(void, treeDatInit)(void) {
static TNimNode* TMP124[3];
static TNimNode TMP122[4];
NTI77089.size = sizeof(tbinarytree77089);
NTI77089.kind = 18;
NTI77089.base = 0;
TMP124[0] = &TMP122[1];
TMP122[1].kind = 1;
TMP122[1].offset = offsetof(tbinarytree77089, Le);
TMP122[1].typ = (&NTI77086);
TMP122[1].name = "le";
TMP124[1] = &TMP122[2];
TMP122[2].kind = 1;
TMP122[2].offset = offsetof(tbinarytree77089, Ri);
TMP122[2].typ = (&NTI77086);
TMP122[2].name = "ri";
TMP124[2] = &TMP122[3];
TMP122[3].kind = 1;
TMP122[3].offset = offsetof(tbinarytree77089, Data);
TMP122[3].typ = (&NTI142);
TMP122[3].name = "data";
TMP122[0].len = 3; TMP122[0].kind = 2; TMP122[0].sons = &TMP124[0];
NTI77089.node = &TMP122[0];
NTI77086.size = sizeof(tbinarytree77089*);
NTI77086.kind = 22;
NTI77086.base = (&NTI77089);
NTI77086.flags = 2;
NTI77086.marker = TMP125;
}

