/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rahul/projects/Nimrod/lib -o /home/rahul/musings/nimrod/nimcache/nimrod_expr.o /home/rahul/musings/nimrod/nimcache/nimrod_expr.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct pexprHEX3Aobjecttype77008 pexprHEX3Aobjecttype77008;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct pliteralHEX3Aobjecttype77009 pliteralHEX3Aobjecttype77009;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct pplusexprHEX3Aobjecttype77011 pplusexprHEX3Aobjecttype77011;
typedef struct tcell38648 tcell38648;
typedef struct tcellseq38664 tcellseq38664;
typedef struct tgcheap40616 tgcheap40616;
typedef struct tcellset38660 tcellset38660;
typedef struct tpagedesc38656 tpagedesc38656;
typedef struct tmemregion22010 tmemregion22010;
typedef struct tsmallchunk21238 tsmallchunk21238;
typedef struct tllchunk22004 tllchunk22004;
typedef struct tbigchunk21240 tbigchunk21240;
typedef struct tintset21215 tintset21215;
typedef struct ttrunk21211 ttrunk21211;
typedef struct tavlnode22008 tavlnode22008;
typedef struct tgcstat40614 tgcstat40614;
typedef struct tbasechunk21236 tbasechunk21236;
typedef struct tfreecell21228 tfreecell21228;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
typedef N_NIMCALL_PTR(void, TY889) (void* p, NI op);
struct TNimType {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY889 marker;
};
struct TNimObject {
TNimType* m_type;
};
struct pexprHEX3Aobjecttype77008 {
  TNimObject Sup;
};
struct pliteralHEX3Aobjecttype77009 {
  pexprHEX3Aobjecttype77008 Sup;
NI X;
};
struct pplusexprHEX3Aobjecttype77011 {
  pexprHEX3Aobjecttype77008 Sup;
pexprHEX3Aobjecttype77008* A;
pexprHEX3Aobjecttype77008* B;
};
struct TNimNode {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tcell38648 {
NI Refcount;
TNimType* Typ;
};
struct tcellseq38664 {
NI Len;
NI Cap;
tcell38648** D;
};
struct tcellset38660 {
NI Counter;
NI Max;
tpagedesc38656* Head;
tpagedesc38656** Data;
};
typedef tsmallchunk21238* TY22022[512];
typedef ttrunk21211* ttrunkbuckets21213[256];
struct tintset21215 {
ttrunkbuckets21213 Data;
};
struct tmemregion22010 {
NI Minlargeobj;
NI Maxlargeobj;
TY22022 Freesmallchunks;
tllchunk22004* Llmem;
NI Currmem;
NI Maxmem;
NI Freemem;
NI Lastsize;
tbigchunk21240* Freechunkslist;
tintset21215 Chunkstarts;
tavlnode22008* Root;
tavlnode22008* Deleted;
tavlnode22008* Last;
tavlnode22008* Freeavlnodes;
};
struct tgcstat40614 {
NI Stackscans;
NI Cyclecollections;
NI Maxthreshold;
NI Maxstacksize;
NI Maxstackcells;
NI Cycletablesize;
NI64 Maxpause;
};
struct tgcheap40616 {
void* Stackbottom;
NI Cyclethreshold;
tcellseq38664 Zct;
tcellseq38664 Decstack;
tcellset38660 Cycleroots;
tcellseq38664 Tempstack;
NI Recgclock;
tmemregion22010 Region;
tgcstat40614 Stat;
};
typedef NI TY21218[8];
struct tpagedesc38656 {
tpagedesc38656* Next;
NI Key;
TY21218 Bits;
};
struct tbasechunk21236 {
NI Prevsize;
NI Size;
NIM_BOOL Used;
};
struct tsmallchunk21238 {
  tbasechunk21236 Sup;
tsmallchunk21238* Next;
tsmallchunk21238* Prev;
tfreecell21228* Freelist;
NI Free;
NI Acc;
NF Data;
};
struct tllchunk22004 {
NI Size;
NI Acc;
tllchunk22004* Next;
};
struct tbigchunk21240 {
  tbasechunk21236 Sup;
tbigchunk21240* Next;
tbigchunk21240* Prev;
NI Align;
NF Data;
};
struct ttrunk21211 {
ttrunk21211* Next;
NI Key;
TY21218 Bits;
};
typedef tavlnode22008* TY22014[2];
struct tavlnode22008 {
TY22014 Link;
NI Key;
NI Upperbound;
NI Level;
};
struct tfreecell21228 {
tfreecell21228* Next;
NI Zerofield;
};
N_NIMCALL(NI, eval_77018)(pexprHEX3Aobjecttype77008* e);
N_NIMCALL(void, quit_74829)(NimStringDesc* errormsg, NI errorcode);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, eval_77029)(pliteralHEX3Aobjecttype77009* e);
N_NIMCALL(NI, eval_77035)(pplusexprHEX3Aobjecttype77011* e);
N_NIMCALL(NI, eval_77024)(pexprHEX3Aobjecttype77008* e);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(pliteralHEX3Aobjecttype77009*, newlit_77041)(NI x);
N_NIMCALL(void, TMP126)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(pplusexprHEX3Aobjecttype77011*, newplus_77048)(pexprHEX3Aobjecttype77008* a, pexprHEX3Aobjecttype77008* b);
N_NIMCALL(void, TMP128)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP129)(void* p, NI op);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tcell38648*, usrtocell_42039)(void* usr);
static N_INLINE(void, rtladdzct_43602)(tcell38648* c);
N_NOINLINE(void, addzct_42015)(tcellseq38664* s, tcell38648* c);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NIM_BOOL, isObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, exprInit)(void);
N_NOINLINE(void, exprDatInit)(void);
STRING_LITERAL(TMP124, "To be overridden", 16);
extern TFrame* frameptr_11825;
extern TNimType NTI1009; /* TObject */
TNimType NTI77008; /* PExpr:ObjectType */
TNimType NTI77009; /* PLiteral:ObjectType */
extern TNimType NTI105; /* int */
TNimType NTI77005; /* PLiteral */
TNimType NTI77011; /* PPlusExpr:ObjectType */
TNimType NTI77003; /* PExpr */
TNimType NTI77007; /* PPlusExpr */
extern tgcheap40616 gch_40644;

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_11825;
	frameptr_11825 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_11825 = (*frameptr_11825).prev;
}
N_NIMCALL(NI, eval_77018)(pexprHEX3Aobjecttype77008* e) {
	NI result;
	nimfr("eval", "expr.nim")
	result = 0;
	nimln(9, "expr.nim");
	quit_74829(((NimStringDesc*) &TMP124), 1);	popFrame();
	return result;
}
N_NIMCALL(NI, eval_77029)(pliteralHEX3Aobjecttype77009* e) {
	NI result;
	nimfr("eval", "expr.nim")
	result = 0;
	nimln(11, "expr.nim");
	result = (*e).X;
	popFrame();
	return result;
}
static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}	LA5: ;
	raiseOverflow();	BeforeRet: ;	return result;
}
N_NIMCALL(NI, eval_77035)(pplusexprHEX3Aobjecttype77011* e) {
	NI result;
	NI LOC1;
	NI LOC2;
	NI TMP125;
	nimfr("eval", "expr.nim")
	result = 0;
	nimln(12, "expr.nim");
	nimln(12, "expr.nim");
	nimln(12, "expr.nim");
	LOC1 = 0;
	LOC1 = eval_77024((*e).A);
	nimln(12, "expr.nim");
	LOC2 = 0;
	LOC2 = eval_77024((*e).B);
	TMP125 = addInt(LOC1, LOC2);
	result = (NI64)(TMP125);
	popFrame();
	return result;
}N_NIMCALL(void, TMP126)(void* p, NI op) {
	pliteralHEX3Aobjecttype77009* a;
	a = (pliteralHEX3Aobjecttype77009*)p;
}

N_NIMCALL(pliteralHEX3Aobjecttype77009*, newlit_77041)(NI x) {
	pliteralHEX3Aobjecttype77009* result;
	pliteralHEX3Aobjecttype77009* LOC1;
	nimfr("newLit", "expr.nim")
	result = 0;
	nimln(14, "expr.nim");
	LOC1 = 0;
	LOC1 = (pliteralHEX3Aobjecttype77009*) newObj((&NTI77005), sizeof(pliteralHEX3Aobjecttype77009));
	(*LOC1).Sup.Sup.m_type = (&NTI77009);
	(*LOC1).X = x;
	result = LOC1;
	popFrame();
	return result;
}N_NIMCALL(void, TMP128)(void* p, NI op) {
	pexprHEX3Aobjecttype77008* a;
	a = (pexprHEX3Aobjecttype77008*)p;
}
N_NIMCALL(void, TMP129)(void* p, NI op) {
	pplusexprHEX3Aobjecttype77011* a;
	a = (pplusexprHEX3Aobjecttype77011*)p;
	nimGCvisit((void*)(*a).A, op);
	nimGCvisit((void*)(*a).B, op);
}

static N_INLINE(tcell38648*, usrtocell_42039)(void* usr) {
	tcell38648* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(116, "gc.nim");
	nimln(116, "gc.nim");
	nimln(116, "gc.nim");
	result = ((tcell38648*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tcell38648))))));
	popFrame();
	return result;
}
static N_INLINE(void, rtladdzct_43602)(tcell38648* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(197, "gc.nim");
	addzct_42015(&gch_40644.Zct, c);	popFrame();
}
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(249, "gc.nim");
	{
		tcell38648* c;
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(250, "gc.nim");
		c = usrtocell_42039(src);
		nimln(167, "gc.nim");
		(*c).Refcount += 8;
	}	LA3: ;
	nimln(252, "gc.nim");
	{
		tcell38648* c;
		nimln(698, "system.nim");
		nimln(698, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(253, "gc.nim");
		c = usrtocell_42039((*dest));
		nimln(254, "gc.nim");
		{
			nimln(165, "gc.nim");
			(*c).Refcount -= 8;
			nimln(166, "gc.nim");
			if (!((NU64)((*c).Refcount) < (NU64)(8))) goto LA11;
			nimln(255, "gc.nim");
			rtladdzct_43602(c);		}		LA11: ;
	}	LA7: ;
	nimln(256, "gc.nim");
	(*dest) = src;
	popFrame();
}
N_NIMCALL(pplusexprHEX3Aobjecttype77011*, newplus_77048)(pexprHEX3Aobjecttype77008* a, pexprHEX3Aobjecttype77008* b) {
	pplusexprHEX3Aobjecttype77011* result;
	pplusexprHEX3Aobjecttype77011* LOC1;
	nimfr("newPlus", "expr.nim")
	result = 0;
	nimln(15, "expr.nim");
	LOC1 = 0;
	LOC1 = (pplusexprHEX3Aobjecttype77011*) newObj((&NTI77007), sizeof(pplusexprHEX3Aobjecttype77011));
	(*LOC1).Sup.Sup.m_type = (&NTI77011);
	asgnRefNoCycle((void**) &(*LOC1).A, a);
	asgnRefNoCycle((void**) &(*LOC1).B, b);
	result = LOC1;
	popFrame();
	return result;
}
N_NIMCALL(NI, eval_77024)(pexprHEX3Aobjecttype77008* e) {
	NI result;
	nimfr("eval", "expr.nim")
	result = 0;
	nimln(8, "expr.nim");
	{
		nimln(8, "expr.nim");
		if (!((e) && isObj((*e).Sup.m_type, (&NTI77011)))) goto LA3;
		nimln(8, "expr.nim");
		nimln(8, "expr.nim");
		if (e) chckObj((*e).Sup.m_type, (&NTI77011));
		result = eval_77035(((pplusexprHEX3Aobjecttype77011*) (e)));
		goto BeforeRet;
	}	goto LA1;
	LA3: ;
	{
		nimln(8, "expr.nim");
		if (!((e) && isObj((*e).Sup.m_type, (&NTI77009)))) goto LA6;
		nimln(8, "expr.nim");
		nimln(8, "expr.nim");
		if (e) chckObj((*e).Sup.m_type, (&NTI77009));
		result = eval_77029(((pliteralHEX3Aobjecttype77009*) (e)));
		goto BeforeRet;
	}	goto LA1;
	LA6: ;
	{
		nimln(8, "expr.nim");
		if (!((e) && isObj((*e).Sup.m_type, (&NTI77008)))) goto LA9;
		nimln(8, "expr.nim");
		nimln(8, "expr.nim");
		result = eval_77018(e);
		goto BeforeRet;
	}	goto LA1;
	LA9: ;
	LA1: ;
	BeforeRet: ;	popFrame();
	return result;
}
static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);}int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	systemDatInit();
	exprDatInit();
	initStackBottom();
	systemInit();
	exprInit();
}
int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}
N_NOINLINE(void, exprInit)(void) {
	pliteralHEX3Aobjecttype77009* LOC1;
	pliteralHEX3Aobjecttype77009* LOC2;
	pplusexprHEX3Aobjecttype77011* LOC3;
	pliteralHEX3Aobjecttype77009* LOC4;
	pplusexprHEX3Aobjecttype77011* LOC5;
	NI LOC6;
	NimStringDesc* LOC7;
	nimfr("expr", "expr.nim")
	nimln(17, "expr.nim");
	nimln(17, "expr.nim");
	nimln(17, "expr.nim");
	nimln(17, "expr.nim");
	nimln(17, "expr.nim");
	nimln(17, "expr.nim");
	LOC1 = 0;
	LOC1 = newlit_77041(1);
	nimln(17, "expr.nim");
	LOC2 = 0;
	LOC2 = newlit_77041(2);
	LOC3 = 0;
	LOC3 = newplus_77048(&LOC1->Sup, &LOC2->Sup);
	nimln(17, "expr.nim");
	LOC4 = 0;
	LOC4 = newlit_77041(4);
	LOC5 = 0;
	LOC5 = newplus_77048(&LOC3->Sup, &LOC4->Sup);
	LOC6 = 0;
	LOC6 = eval_77024(&LOC5->Sup);
	LOC7 = 0;
	LOC7 = nimIntToStr(LOC6);
	printf("%s\012", (LOC7)->data);
	popFrame();
}

N_NOINLINE(void, exprDatInit)(void) {
static TNimNode* TMP127[2];
static TNimNode TMP122[5];
NTI77008.size = sizeof(pexprHEX3Aobjecttype77008);
NTI77008.kind = 17;
NTI77008.base = (&NTI1009);
NTI77008.flags = 3;
TMP122[0].len = 0; TMP122[0].kind = 2;
NTI77008.node = &TMP122[0];
NTI77009.size = sizeof(pliteralHEX3Aobjecttype77009);
NTI77009.kind = 17;
NTI77009.base = (&NTI77008);
NTI77009.flags = 3;
TMP122[1].kind = 1;
TMP122[1].offset = offsetof(pliteralHEX3Aobjecttype77009, X);
TMP122[1].typ = (&NTI105);
TMP122[1].name = "x";
NTI77009.node = &TMP122[1];
NTI77005.size = sizeof(pliteralHEX3Aobjecttype77009*);
NTI77005.kind = 22;
NTI77005.base = (&NTI77009);
NTI77005.flags = 2;
NTI77005.marker = TMP126;
NTI77011.size = sizeof(pplusexprHEX3Aobjecttype77011);
NTI77011.kind = 17;
NTI77011.base = (&NTI77008);
NTI77011.flags = 2;
TMP127[0] = &TMP122[3];
NTI77003.size = sizeof(pexprHEX3Aobjecttype77008*);
NTI77003.kind = 22;
NTI77003.base = (&NTI77008);
NTI77003.flags = 2;
NTI77003.marker = TMP128;
TMP122[3].kind = 1;
TMP122[3].offset = offsetof(pplusexprHEX3Aobjecttype77011, A);
TMP122[3].typ = (&NTI77003);
TMP122[3].name = "a";
TMP127[1] = &TMP122[4];
TMP122[4].kind = 1;
TMP122[4].offset = offsetof(pplusexprHEX3Aobjecttype77011, B);
TMP122[4].typ = (&NTI77003);
TMP122[4].name = "b";
TMP122[2].len = 2; TMP122[2].kind = 2; TMP122[2].sons = &TMP127[0];
NTI77011.node = &TMP122[2];
NTI77007.size = sizeof(pplusexprHEX3Aobjecttype77011*);
NTI77007.kind = 22;
NTI77007.base = (&NTI77011);
NTI77007.flags = 2;
NTI77007.marker = TMP129;
}

