/* Generated by Nimrod Compiler v0.9.3 */
/*   (c) 2012 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/rahul/projects/Nimrod/lib -o /home/rahul/musings/nimrod/nimcache/nimrod_range.o /home/rahul/musings/nimrod/nimcache/nimrod_range.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NIM_CHAR TY611[100000001];
struct NimStringDesc {
  TGenericSeq Sup;
TY611 data;
};
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, readline_9280)(FILE* f);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, pureparseutilsInit)(void);
N_NOINLINE(void, pureparseutilsDatInit)(void);
N_NOINLINE(void, purestrutilsInit)(void);
N_NOINLINE(void, purestrutilsDatInit)(void);
N_NOINLINE(void, rangeInit)(void);
N_NOINLINE(void, rangeDatInit)(void);
STRING_LITERAL(TMP128, "A number please: ", 17);
STRING_LITERAL(TMP136, "The number is in the set {0, 1, 2, 4, 5, 6, 7}", 46);
STRING_LITERAL(TMP137, "The number is 3 or 8", 20);
NI n_85003;
extern TFrame* frameptr_11825;

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);}int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	systemDatInit();
	pureparseutilsDatInit();
	purestrutilsDatInit();
	rangeDatInit();
	initStackBottom();
	systemInit();
	pureparseutilsInit();
	purestrutilsInit();
	rangeInit();
}
int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_11825;
	frameptr_11825 = s;
}
static N_INLINE(void, popFrame)(void) {
	frameptr_11825 = (*frameptr_11825).prev;
}N_NOINLINE(void, rangeInit)(void) {
	NimStringDesc* LOC1;
	nimfr("range", "range.nim")
	nimln(3, "range.nim");
	printf("%s\012", (((NimStringDesc*) &TMP128))->data);
	nimln(4, "range.nim");
	nimln(4, "range.nim");
	LOC1 = 0;
	LOC1 = readline_9280(stdin);
	n_85003 = nsuParseInt(LOC1);
	nimln(5, "range.nim");
	switch (n_85003) {
	case 0 ... 2:
	case 4 ... 7:
	{
		nimln(6, "range.nim");
		printf("%s\012", (((NimStringDesc*) &TMP136))->data);
	}	break;
	case 3:
	case 8:
	{
		nimln(7, "range.nim");
		printf("%s\012", (((NimStringDesc*) &TMP137))->data);
	}	break;
	default:
	{
	}	break;
	}
	popFrame();
}

N_NOINLINE(void, rangeDatInit)(void) {
}

